### ISSUE TITLE
Blocklists checklist

### ISSUE THREAD

**Issue by Uinelj** [oscar-project/ungoliant#79]
Some changes are required on blocklist management:

- [x] Use `category` rather than `annotation` when documents are detected on blocklists. _This is to separate quality annotations and topic classification_
- [x] Improve the way the blocklist is built. Currently we might have a number of blocklists in parallel, where we'd only need one. _This may need updating `ut1-rs` to provide some blocklist merging feature._
- [ ] Change the adult content detector so that it only checks if the `adult` category is present in the `category` field, rather than doing the blocklist lookup itself.
